name: test, fmt, clippy

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo check --verbose --manifest-path ./elective/Cargo.toml --workspace
    - name: fmt
      run: cargo fmt --manifest-path ./elective/Cargo.toml --all
    - name: Run tests
      run: cargo test --manifest-path ./elective/Cargo.toml --verbose --workspace

